### ISSUE TITLE
Thumbnail gone rogue

### ISSUE THREAD

**Issue by alycechen** [labsyspharm/harvardtissueatlas#110]
https://www.ludwigtumoratlas.org/
second row of images, far right is not displaying correctly (Genetically engineered mouse model of lung adenocarcinoma). At least not on my apple MacBook Pro via Chrome.

**Comment by alycechen** [comment]
also here, for the same minerva story, I think: https://www.ludwigtumoratlas.org/data
(about 4/5 of the way down the page)

**Comment by arenasg** [comment]
This image issue has been resolved!
