### ISSUE TITLE
Broken data set link for lin-chen-campton-2023

### ISSUE THREAD

**Issue by alycechen** [labsyspharm/harvardtissueatlas#111]
On this page: https://www.ludwigtumoratlas.org/publications
The High-plex immunofluorescence imaging and traditional histology of the same tissue section for discovering image-based biomarkers data set link leads to https://www.ludwigtumoratlas.org/atlas-datasets/lin-chen-campton-2023/ which is a 404 error.

**Comment by arenasg** [comment]
Alyce, I realized the actual issue is that the Ludwig site does not yet allow for dataset pages. I'll hide this link for now and will show it again once this feature is available on this site.

**Comment by arenasg** [comment]
I'll close this issue for now, but I have adding the landing pages to the Ludwig site as a future update. 

As a temporary work around, the Ludwig "atlas dataset" links redirect to the tissue-atlas site. This gives website visitors access to the correct content but I recognize will be confusing for users to land on a new site.
