### ISSUE TITLE
broken link on https://www.tissue-atlas.org/funding

### ISSUE THREAD

**Issue by alycechen** [labsyspharm/harvardtissueatlas#113]
on https://www.tissue-atlas.org/funding, the link for Gray Foundation Basser Initiative  (https://www.grayfoundation.org/program-areas/basser/) is broken.

**Comment by arenasg** [comment]
Updated to the new BRCA link: [https://grayfoundation.org/program-areas/brca-initiatives/](https://grayfoundation.org/program-areas/brca-initiatives/)
